/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConnectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccounts"];
        put?: never;
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listJobs"];
        put?: never;
        post: operations["submitJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/run-next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runNextJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replayJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listJobAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        JobStatus: "QUEUED" | "RUNNING" | "RETRY_WAIT" | "SUCCEEDED" | "DEAD_LETTERED" | "CANCELLED";
        /** @enum {string} */
        FailurePlan: "NONE" | "RATE_LIMIT_ONCE" | "TRANSIENT_TWICE" | "PERMANENT";
        ConnectorDescriptor: {
            id: string;
            displayName: string;
        };
        ConnectorAccount: {
            /** Format: uuid */
            id: string;
            connectorId: string;
            displayName: string;
            externalReference: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateAccountRequest: {
            connectorId: string;
            displayName: string;
            externalReference: string;
        };
        SubmitJobRequest: {
            /** Format: uuid */
            accountId: string;
            failurePlan: components["schemas"]["FailurePlan"];
            maxAttempts: number;
        };
        SyncJob: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            accountId: string;
            status: components["schemas"]["JobStatus"];
            failurePlan: components["schemas"]["FailurePlan"];
            attempt: number;
            maxAttempts: number;
            pageCursor?: string | null;
            /** Format: date-time */
            availableAt: string;
            correlationId: string;
            idempotencyKey: string;
            lastError?: string | null;
            recordsProcessed: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AuditEvent: {
            /** Format: int64 */
            id: number;
            /** Format: uuid */
            jobId: string;
            eventType: string;
            actor: string;
            detail: string;
            /** Format: date-time */
            occurredAt: string;
        };
        AccountMutationResult: {
            resource: components["schemas"]["ConnectorAccount"];
            created: boolean;
        };
        JobMutationResult: {
            resource: components["schemas"]["SyncJob"];
            created: boolean;
        };
        JobPage: {
            items: components["schemas"]["SyncJob"][];
            nextCursor?: string | null;
        };
        RunNextResult: {
            job?: components["schemas"]["SyncJob"] | null;
            workAvailable: boolean;
        };
        Dashboard: {
            statusCounts: {
                [key: string]: number;
            };
            recentJobs: components["schemas"]["SyncJob"][];
        };
        Problem: {
            /** Format: uri */
            type?: string;
            title: string;
            status: number;
            detail: string;
            /** Format: uri */
            instance?: string;
        };
    };
    responses: {
        /** @description RFC 9457 problem detail */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        JobId: string;
        /** @description Demonstration-only role boundary; not production authentication. */
        DemoRole: "viewer" | "operator";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listConnectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available fake connectors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorDescriptor"][];
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Linked fake accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorAccount"][];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description Demonstration-only role boundary; not production authentication. */
                "X-Demo-Role": components["parameters"]["DemoRole"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Existing account returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountMutationResult"];
                };
            };
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountMutationResult"];
                };
            };
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    listJobs: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Keyset-paginated jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    submitJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Demonstration-only role boundary; not production authentication. */
                "X-Demo-Role": components["parameters"]["DemoRole"];
                "Idempotency-Key": string;
                "X-Demo-Actor"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitJobRequest"];
            };
        };
        responses: {
            /** @description Existing idempotent job returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobMutationResult"];
                };
            };
            /** @description Job accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobMutationResult"];
                };
            };
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    runNextJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Demonstration-only role boundary; not production authentication. */
                "X-Demo-Role": components["parameters"]["DemoRole"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scheduler result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunNextResult"];
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJob"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    runJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Demonstration-only role boundary; not production authentication. */
                "X-Demo-Role": components["parameters"]["DemoRole"];
            };
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJob"];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Demonstration-only role boundary; not production authentication. */
                "X-Demo-Role": components["parameters"]["DemoRole"];
            };
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJob"];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    replayJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Demonstration-only role boundary; not production authentication. */
                "X-Demo-Role": components["parameters"]["DemoRole"];
            };
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requeued job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJob"];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listJobAudit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chronological append-only audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operational summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
}
