-- File: V1__operations_schema.sql
-- Purpose: Durable relational model for accounts, jobs, idempotency, and audit events.
-- Objects: connector_accounts, sync_jobs, audit_events, and scheduler/listing indexes.
-- Complexity: indexed scheduler lookup is O(log n + k); keyed lookups are O(log n).

CREATE TABLE connector_accounts (
  id UUID PRIMARY KEY,
  connector_id VARCHAR(40) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  external_reference VARCHAR(120) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uq_connector_external UNIQUE (connector_id, external_reference)
);

CREATE TABLE sync_jobs (
  id UUID PRIMARY KEY,
  account_id UUID NOT NULL REFERENCES connector_accounts(id),
  status VARCHAR(24) NOT NULL,
  failure_plan VARCHAR(24) NOT NULL,
  attempt INTEGER NOT NULL CHECK (attempt >= 0),
  max_attempts INTEGER NOT NULL CHECK (max_attempts BETWEEN 1 AND 10),
  page_cursor VARCHAR(160),
  available_at TIMESTAMP WITH TIME ZONE NOT NULL,
  correlation_id VARCHAR(80) NOT NULL,
  idempotency_key VARCHAR(100) NOT NULL UNIQUE,
  last_error VARCHAR(300),
  records_processed INTEGER NOT NULL CHECK (records_processed >= 0),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT ck_sync_job_status CHECK (
    status IN ('QUEUED', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'DEAD_LETTERED', 'CANCELLED')
  ),
  CONSTRAINT ck_sync_job_failure_plan CHECK (
    failure_plan IN ('NONE', 'RATE_LIMIT_ONCE', 'TRANSIENT_TWICE', 'PERMANENT')
  )
);

CREATE INDEX idx_sync_jobs_scheduler
  ON sync_jobs (status, available_at, created_at);
CREATE INDEX idx_sync_jobs_listing
  ON sync_jobs (updated_at DESC, id DESC);

CREATE TABLE audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id UUID NOT NULL REFERENCES sync_jobs(id),
  event_type VARCHAR(40) NOT NULL,
  actor VARCHAR(100) NOT NULL,
  detail VARCHAR(500) NOT NULL,
  occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_events_job_time
  ON audit_events (job_id, occurred_at, id);
